quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/books20262026
quarkus.datasource.username=postgres
#quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.password=Badboy22
quarkus.http.port=8080
quarkus.http.host=0.0.0.0

#authors.url.lb=localhost:8070,localhost:8071
#quarkus.stork.authors-api.service-discovery.type=static
#quarkus.stork.authors-api.service-discovery.address-list=${authors.url.lb}
#quarkus.stork.authors-api.load-balancer.type=round-robin

# Run flyway migration automatically at startup
#quarkus.flyway.migrate-at-start=true
#quarkus.package.jar.type = uber-jar

quarkus.stork.authors-api.service-discovery.type=consul
quarkus.stork.authors-api.service-discovery.consul-host=${consul.host}
quarkus.stork.authors-api.service-discovery.consul-port=${consul.port}
quarkus.stork.authors-api.service-discovery.application=app-authors
quarkus.stork.authors-api.service-discovery.refresh-period=5s

#-CORS
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=/.*/
quarkus.http.cors.methods=GET,POST,PUT,DELETE

# optional default to the system username
quarkus.container-image.group=michaelbarrionuevo

# optional default to the aplication name
quarkus.container-image.name=app-books

# optional default to the application version
quarkus.container-image.tag=latest

quarkus.kubernetes.en.vars=QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres:5432/books-db


quarkus.otel.service.name=app-books


quarkus.otel.enabled=true


quarkus.otel.exporter.otlp.traces.endpoint=http://jaeger:4317