worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}


http {
   upstream app-authors {
        server localhost:8070;
        server localhost:8071;
    }

   upstream app-books {
           server localhost:8080;
           server localhost:8081;
       }
    server {
        listen 80;

        location /app-authors/ {
            proxy_pass http://app-authors/;
        }

        location /app-books/ {
                    proxy_pass http://app-books/;
        }
    }
}
 