server:
  port: 8090
spring:
  application:
    name: app-customers
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:

        health-check-path: /actuator/health
        health-check-interval: 10s
        instance-id: ${spring.application.name}-${random.value}
        tags:
          - framework=springboot-4.0.6
          - traefik.enable=true
          - traefik.http.routers.router-app-customers.rule=PathPrefix(`/app-customers`)
          - traefik.http.routers.router-app-customers.middlewares=middleware-customers
          - traefik.http.middlewares.middleware-customers.stripprefix.prefixes=/app-customers
management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health,info"