quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/books20262026
quarkus.datasource.username=postgres
#quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.password=Badboy22
quarkus.http.port=8070
quarkus.http.host=0.0.0.0
# Run flyway migration automatically at startup
quarkus.flyway.migrate-at-start=true
#quarkus.package.jar.type = uber-jar

#--CORS
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=/.*/
quarkus.http.cors.methods=GET,POST,PUT,DELETE