CREATE TABLE customers
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email   VARCHAR(255),
    name    VARCHAR(255),
    version INTEGER                                  NOT NULL,
    CONSTRAINT pk_customers PRIMARY KEY (id)
);