CREATE TABLE line_items
(
    idx       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    quantity  INTEGER                                  NOT NULL,
    book_isbn VARCHAR(255),
    order_id  INTEGER,
    CONSTRAINT pk_line_items PRIMARY KEY (idx)
);