CREATE TABLE purchase_orders
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    deliveredon TIMESTAMP WITHOUT TIME ZONE,
    placedon    TIMESTAMP WITHOUT TIME ZONE,
    status      INTEGER                                  NOT NULL,
    total       INTEGER                                  NOT NULL,
    customer_id INTEGER,
    CONSTRAINT pk_purchase_orders PRIMARY KEY (id)
);