CREATE TABLE authors
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_authors PRIMARY KEY (id)
);

insert into authors (name)
values ('Byron Flores');
insert
into authors (name)
values ('Marco Perez');
insert into authors (name)
values ('Jose Espin');
